language: ruby
rvm:
  - 2.5.1
services:
  - postgresql

before_script:
  - psql -c 'create database rails_playground_test;' -U postgres

before_install:
  - gem update --system
  - gem install bundler